server:
  port: 8082
spring:
  application:
    name: "temperature-microservice"
eureka:
  instance:
    preferIpAddress: true
    ip-address: host.docker.internal
  client:
    serviceUrl:
      defaultZone: "http://host.docker.internal:8761/eureka"